project_id: '574795'
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  # JSON translation files
  - source: /docs/i18n/en/**/*
    translation: /docs/i18n/%two_letters_code%/**/%original_file_name%
  # Docs Markdown files
  - source: /docs/docs/**/*
    translation: /docs/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
  # Blog Markdown files
  - source: /docs/blog/**/*
    translation: /docs/i18n/%two_letters_code%/docusaurus-plugin-content-blog/**/%original_file_name%